version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_app
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/code/app
      - ./backend/alembic.ini:/code/alembic.ini
      - ./backend/migrations:/code/migrations
    env_file:
      - .env
    environment:
      - PYTHONPATH=/code

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_app
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  db_data:
