FROM python:3.11

WORKDIR /code

COPY ./app /code/app
COPY requirements.txt /code/requirements.txt
COPY alembic.ini /code/alembic.ini
COPY ./migrations /code/migrations

RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r /code/requirements.txt

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
